services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-secret"
      - key: EMAIL_HOST_USER
        value: "your-email@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "your-app-password"
      - key: RAZORPAY_KEY_ID
        value: "your-razorpay-id"
      - key: RAZORPAY_KEY_SECRET
        value: "your-razorpay-secret"
